export const COMETCHAT_CONSTANTS = {
  NO_ITEM_SELECTED_MESSAGE:
    "Sélectionnez une discussion pour commencer à échanger",
  LOADING_MESSSAGE: "Chargement...",
  ADDING_MESSSAGE: "Ajout...",
  CREATING_MESSSAGE: "Création...",
  SEARCH_LOADING: "Recherche en cours...",
  ERROR_LOADING_USERS: "Erreur lors du chargement des utilisateurs",
  ERROR_LOADING_CHATS: "Erreur lors du chargement des discussions",
  ERROR_COMETCHAT_LOGIN: "Erreur de connexion, rechargez",
  ERROR_NO_USERS_FOUND: "Aucun utilisateur trouvé",
  EMPTY_STRING: "",
  SINGLE_SPACE: " ",
  USERS: "Utilisateurs",
  CHATS: "Discussions",
  GROUPS: "Groupes",
  IGNORE: "Ignorer",
  MORE: "Plus",
  MESSAGE_IMAGE: "📷 Image",
  MESSAGE_FILE: "📁 Fichier",
  MESSAGE_VIDEO: "🎥 Vidéo",
  MESSAGE_AUDIO: "🎵 Audio",
  CUSTOM_MESSAGE: "Vous avez un message",
  MISSED_VOICE_CALL: "Appel vocal manqué",
  MISSED_VIDEO_CALL: "Appel vidéo manqué",
  CALL_UNANSWERED: "Appel non répondu",
  MISSED_AUDIO_CALL: "Appel audio manqué",
  CUSTOM_MESSAGE_POLL: "📊 Sondage",
  CUSTOM_MESSAGE_STICKER: "💟 Autocollant",
  CUSTOM_MESSAGE_DOCUMENT: "📃 Document",
  CUSTOM_MESSAGE_WHITEBOARD: "📝 Tableau blanc",
  ONLINE: "En ligne",
  ADMINISTRATOR: "Administrateur",
  MODERATOR: "Modérateur",
  PARTICIPANT: "Participant",
  PUBLIC: "Public",
  PRIVATE: "Privé",
  PASSWORD_PROTECTED: "Protégé par mot de passe",
  PRIVACY_AND_SECURITY: "Vie privée et sécurité",
  PREFERENCES: "Préférences",
  MEMBERS: "Membres",
  TODAY: "Aujourd'hui",
  YESTERDAY: "Hier",
  TYPING: "en train d'écrire...",
  IS_TYPING: "est en train d'écrire...",
  CLOSE: "Fermer",
  ENTER_GROUP_NAME: "Saisissez le nom du groupe",
  ADD_MEMBERS: "Ajouter des membres",
  SEND_MESSAGE: "Envoyer un message",
  UNBLOCK_USER: "Débloquer l'utilisateur",
  BLOCK_USER: "Bloquer l'utilisateur",
  DELETE_AND_EXIT: "Supprimer et quitter",
  LEAVE_GROUP: "Quitter le groupe",
  SHARED_MEDIA: "Médias partagés",
  VIDEO_CALL: "Appel vidéo",
  AUDIO_CALL: "Appel audio",
  REPLY: "répondre",
  REPLIES: "réponses",
  LAUNCH: "Lancer",
  SHARED_COLLABORATIVE_DOCUMENT: "a partagé un document collaboratif",
  SHARED_COLLABORATIVE_WHITEBOARD: "a partagé un tableau blanc collaboratif",
  CREATED_WHITEBOARD: "Vous avez créé un nouveau tableau blanc collaboratif",
  CREATED_DOCUMENT: "Vous avez créé un nouveau document collaboratif",
  PHOTOS: "Photos",
  VIDEOS: "Vidéos",
  DOCUMENT: "Document",
  YOU_DELETED_THIS_MESSAGE: "⚠️ Vous avez supprimé ce message",
  THIS_MESSAGE_DELETED: "⚠️ Ce message a été supprimé",
  VIEW_ON_YOUTUBE: "Voir sur Youtube",
  SEARCH: "Rechercher",
  NO_USERS_FOUND: "Aucun utilisateur trouvé",
  ERROR: "Erreur",
  NO_GROUPS_FOUND: "Aucun groupe trouvé",
  NO_CHATS_FOUND: "Aucune",
  MEDIA_MESSAGE: "Message multimédia",
  INCOMING_AUDIO_CALL: "Appel audio entrant",
  INCOMING_VIDEO_CALL: "Appel vidéo entrant",
  DECLINE: "Refuser",
  ACCEPT: "Accepter",
  CALL_INITIATED: "Appel initié",
  OUTGOING_AUDIO_CALL: "Appel audio sortant",
  OUTGOING_VIDEO_CALL: "Appel vidéo sortant",
  CALL_REJECTED: "Appel rejeté",
  REJECTED_CALL: "Appel rejeté",
  CALL_ACCEPTED: "Appel accepté",
  JOINED: "a rejoint",
  LEFT_THE_CALL: "a quitté l'appel",
  UNANSWERED_AUDIO_CALL: "Appel audio sans réponse",
  UNANSWERED_VIDEO_CALL: "Appel vidéo sans réponse",
  CALL_ENDED: "Appel terminé",
  CALL_CANCELLED: "Appel annulé",
  CALL_BUSY: "Appel occupé",
  CALLING: "Appel en cours...",
  ADD: "Ajouter",
  NO_BANNED_MEMBERS_FOUND: "Aucun membre banni trouvé",
  BANNED_MEMBERS: "Membres bannis",
  NAME: "Nom",
  SCOPE: "Portée",
  UNBAN: "Débannir",
  SELECT_GROUP_TYPE: "Sélectionnez le type de groupe",
  ENTER_GROUP_PASSWORD: "Entrer le mot de passe du groupe",
  CREATE: "Créer",
  CREATE_GROUP: "Créer un groupe",
  CREATE_POLL: "Créer un sondage",
  QUESTION: "Question",
  ENTER_YOUR_QUESTION: "Entrez votre question",
  OPTIONS: "Options",
  ENTER_YOUR_OPTION: "Entrez votre option",
  ADD_NEW_OPTION: "Ajouter une nouvelle option",
  VIEW_MEMBERS: "Voir les membres",
  DETAILS: "Détails",
  NOTIFICATIONS: "Notifications",
  OTHER: "Autre",
  HELP: "Aide",
  REPORT_PROBLEM: "Signaler un problème",
  GROUP_MEMBERS: "Membres du groupe",
  BAN: "Bannir",
  KICK: "Expulser",
  PICK_YOUR_EMOJI: "Choisissez votre emoji",
  PRIVATE_GROUP: "Groupe privé",
  PROTECTED_GROUP: "Groupe protégé",
  VISIT: "Visiter",
  ATTACH: "Joindre",
  ATTACH_FILE: "Joindre un fichier",
  ATTACH_VIDEO: "Joindre une vidéo",
  ATTACH_AUDIO: "Joindre un fichier audio",
  ATTACH_IMAGE: "Joindre une image",
  //
  COLLABORATE_USING_DOCUMENT: "Collaborer en utilisant un document",
  COLLABORATE_USING_WHITEBOARD: "Collaborer en utilisant un tableau blanc",
  ADD_EMOJI: "Ajouter un emoji",
  EMOJI: "Emoji",
  ENTER_YOUR_MESSAGE_HERE: "Entrez votre message ici",
  NO_MESSAGES_FOUND: "Aucun message trouvé",
  THREAD: "Fil de discussion",
  COLLABORATIVE_DOCUMENT: "Document collaboratif",
  COLLABORATIVE_WHITEBOARD: "Tableau blanc collaboratif",
  ADD_REACTION: "Ajouter une réaction",
  HEART: "coeur",
  NO_STICKERS_FOUND: "Aucun autocollant trouvé",
  REPLY_TO_THREAD: "Répondre au fil",
  REPLY_IN_THREAD: "Répondre dans le fil",
  DELETE_MESSAGE: "Supprimer le message",
  EDIT_MESSAGE: "Modifier le message",
  SUNDAY: "DIMANCHE",
  MONDAY: "LUNDI",
  TUESDAY: "MARDI",
  WEDNESDAY: "MERCREDI",
  THURSDAY: "JEUDI",
  FRIDAY: "VENDREDI",
  SATURDAY: "SAMEDI",
  GROUP_NAME_BLANK: "Le nom du groupe ne peut pas être vide",
  GROUP_TYPE_BLANK: "Le type de groupe ne peut pas être vide",
  GROUP_PASSWORD_BLANK: "Le mot de passe du groupe ne peut pas être vide",
  POLL_QUESTION_BLANK: "La question ne peut pas être vide",
  POLL_OPTION_BLANK: "L'option ne peut pas être vide",
  OWNER: "propriétaire",
  CALLS: "Appels",
  CUSTOM_MESSAGE_LOCATION: "📍Emplacement",
  YOU: "Vous",
  PRIVACY: "Confidentialité",
  BLOCKED_USERS: "Utilisateurs bloqués",
  "YOU'VE_BLOCKED": "Vous avez bloqué",
  NO_PHOTOS: "Aucune photo",
  NO_VIDEOS: "Aucune vidéo",
  NO_DOCUMENTS: "Aucun document",
  NO_RECORDS_FOUND: "Aucun enregistrement trouvé.",
  JOIN: "Rejoindre",
  SENT: "envoyé",
  DELIVERED: "livré",
  ENTER_YOUR_PASSWORD: "Entrez votre mot de passe",
  LAST_ACTIVE_AT: "Dernière activité à :",
  REACTED: "réagi",
  DELETE_CONVERSATION: "Voulez-vous supprimer la conversation ?",
  DELETE_BUTTON_TEXT: "Supprimer",
  CANCEL_BUTTON_TEXT: "Annuler",
};
